export enum EEnvironmentConstants {
  port = 'PORT',
  redisHost = 'REDIS_HOST',
  redisPort = 'REDIS_PORT',
  redisPassword = 'REDIS_PASSWORD',
  redisUsername = 'REDIS_USERNAME',
  redisUrl = 'REDIS_URL',
  nodeEnv = 'NODE_ENV',
  jwtSecret = 'JWT_SECRET',
  jwtExpiration = 'JWT_EXPIRATION',
  encryptionKey = 'ENCRYPTION_KEY',
  encryptionIV = 'ENCRYPTION_IV',
  emailUsername = 'EMAIL_USERNAME',
  emailPassword = 'EMAIL_PASSWORD',
  emailHost = 'EMAIL_HOST',
  emailPort = 'EMAIL_PORT',
  exchangeRateApiKey = 'EXCHANGE_RATE_API_KEY',
}
