export const FleetBaseRequestPattern = 'fleet.service';

export const getFleetPattern = (pattern: string) => {
  return `${FleetBaseRequestPattern}:${pattern}`;
};

export enum FleetPatterns {
  createCategory = 'createCategory',
  getCategories = 'getCategories',
  searchCategories = 'searchCategories',
  getSubCategories = 'getSubCategories',
  searchSubCategories = 'searchSubCategories',
  getBusinesses = 'getBusinesses',
  getBusiness = 'getBusiness',
  getBusinessMinimumPayablePercentage = 'getBusinessMinimumPayablePercentage',
  getBusinessName = 'getBusinessName',
  getVerificationDocuments = 'getVerificationDocuments',
  getVerificationDocument = 'getVerificationDocument',
  approveBusinessVerification = 'approveBusinessVerification',
  rejectBusinessVerification = 'rejectBusinessVerification',
  getServices = 'getServices',
  getAvailability = 'getAvailability',
  fetchAvailabilities = 'fetchAvailabilities',
  addStaffAvailabilities = 'addStaffAvailabilities',
  getServiceProfessionals = 'getServiceProfessionals',
  createSubCategory = 'createSubCategory',
  getBusinessesById = 'getBusinessesById',
  getUserAndBusinessDetails = 'getUserAndBusinessDetails',
  sendInAppNotification = 'sendInAppNotification',
  getServicesByIds = 'getServicesByIds',
  updateSubCategory = 'updateSubCategory',
  updateCategory = 'updateCategory',
  addReview = 'addReview',
  getReviews = 'getReviews',
  addBusinessActivity = 'addBusinessActivity',
  reportBusiness = 'reportBusiness',
  blockBusiness = 'blockBusiness',
  unblockBusiness = 'unblockBusiness',
  getBusinessCustomer = 'getBusinessCustomer',
  getBusinessFee = 'getBusinessFee',
  updateBusinessFee = 'updateBusinessFee',
  updateBusinessFeeNonePartners = 'updateBusinessFeeNonePartners',
  getPayoutTransferRecipients = 'getPayoutTransferRecipients',
  getBusinessServices = 'getBusinessServices',
  getService = 'getService',
  updateService = 'updateService',
  getBusinessStaffs = 'getBusinessStaffs',
  createService = 'createService',
  approveBusinessWithoutVerification = 'approveBusinessWithoutVerification',
}
